name: Build & Push Image (Reusable)

on:
  workflow_call:
    outputs:
      build:
        description: "Image that was built"
        value: ${{ jobs.build_and_push.outputs.image }}
    inputs:
      image_tag:
        description: 'The tag to use for the Docker image'
        required: true
        type: string
      environment:
        description: 'The environment for the workflow'
        required: true
        type: string
      dockerfile:
        description: 'Path to the Dockerfile'
        required: false
        type: string
        default: 'Dockerfile'
    secrets:
      ECR_REPO: {}

jobs:
  build_and_push:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: build
        run: |
          IMAGE_TAG=${{ inputs.image_tag }}
          echo "Building Docker image with tag $IMAGE_TAG..."
          docker build -t ${{ secrets.ECR_REPO }}:$IMAGE_TAG -f ${{ inputs.dockerfile }} .
          echo "Built image: ${{ secrets.ECR_REPO }}:$IMAGE_TAG"
          echo "image=${{ secrets.ECR_REPO }}:$IMAGE_TAG" >> $GITHUB_OUTPUT
        shell: bash
  
      - name: Push Docker image
        id: push
        run: |
          IMAGE_TAG=${{ inputs.image_tag }}
          echo "Pushing Docker image with tag $IMAGE_TAG..."
          docker push ${{ secrets.ECR_REPO }}:$IMAGE_TAG
        shell: bash
