name: Delete ECR Image Tag

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      region:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  delete-ecr-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Delete tag '${{ inputs.tag }}' from ECR
        run: |
          echo "🧼 Deleting tag '${{ inputs.tag }}' from ECR repo '${{ inputs.repo }}' in region '${{ inputs.region }}'..."

          DIGEST=$(aws ecr list-images \
            --repository-name "${{ inputs.repo }}" \
            --region "${{ inputs.region }}" \
            --filter tagStatus=TAGGED \
            --query "imageIds[?contains(imageTag, \`${{ inputs.tag }}\`)].imageDigest" \
            --output text)

          if [[ -n "$DIGEST" ]]; then
            aws ecr batch-delete-image \
              --repository-name "${{ inputs.repo }}" \
              --region "${{ inputs.region }}" \
              --image-ids imageDigest="$DIGEST",imageTag="${{ inputs.tag }}"
            echo "✅ Deleted tag '${{ inputs.tag }}'."
          else
            echo "ℹ️ Tag '${{ inputs.tag }}' not found, skipping."
          fi
