name: Delete ECR Tag (Reusable)

on:
  workflow_call:
    inputs:
      tag:
        description: "The image tag to delete from ECR"
        required: true
        type: string
      environment:
        description: 'The environment for the workflow'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID: {}
      AWS_SECRET_ACCESS_KEY: {}
      ECR_REPO: {}

jobs:
  delete-tag:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete specified tag from ECR
        run: |
          TAG_TO_DELETE=${{ inputs.tag }}
          echo "🧼 Deleting tag '$TAG_TO_DELETE' from ECR repo '${{ secrets.ECR_REPO }}' in region '${{ vars.AWS_REGION }}'..."
          
          aws ecr batch-delete-image \
            --repository-name "${{ vars.REPO_NAME }}" \
            --region "${{ vars.AWS_REGION }}" \
            --image-ids imageTag="$TAG_TO_DELETE"
          
          echo "✅ Deleted tag '$TAG_TO_DELETE'."
