name: PR Checks (Reusable)

on:
  workflow_call:
    inputs:
      branch_regex:
        description: 'Regex to validate the source branch name'
        required: true
        type: string
      verify_workflow:
        description: 'The reusable verification workflow to call (e.g., "verify-dotnet.yml" or "verify-node.yml")'
        required: true
        type: string
      dotnet_version:
        description: 'The .NET version to set up (if applicable)'
        required: false
        type: string
        default: '9.0.x'
      environment:
        description: 'The environment in which to run the tests (e.g., development)'
        required: true
        type: string

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      valid_branch: ${{ steps.validate.outputs.valid_branch }}
    steps:
      - name: Validate source branch name
        id: validate
        run: |
          BRANCH="${{ github.head_ref }}"
          echo "Source branch: $BRANCH"
          regex="${{ inputs.branch_regex }}"
          if [[ "$BRANCH" =~ $regex ]]; then
            echo "✅ Valid branch: $BRANCH"
            echo "valid_branch=true" >> $GITHUB_OUTPUT
          else
            echo "⛔ Invalid branch: $BRANCH"
            echo "valid_branch=false" >> $GITHUB_OUTPUT
            exit 1
          fi

  verify:
    needs: check-branch
    if: needs.check-branch.outputs.valid_branch == 'true'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Run .NET verification
        if: ${{ inputs.verify_workflow == 'dotnet' }}
        uses: ./.github/workflows/reusable/verify-dotnet.yml
        with:
          dotnet_version: ${{ inputs.dotnet_version }}
      - name: Run Node verification
        if: ${{ inputs.verify_workflow == 'node' }}
        uses: ./.github/workflows/reusable/verify-node.yml
