name: PR Checks (.NET - to develop or main)

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]

jobs:
  check-branch:
    uses: kikeiz/shared-workflows/.github/workflows/validate-branch-name.yml@v1
    with:
      branch_regex: '^(feature|bugfix)/ACTO-[0-9]{4,7}(-[A-Za-z0-9]+)+$'

  verify:
    needs: check-branch
    uses: kikeiz/shared-workflows/.github/workflows/verify-dotnet.yml@v1