name: PR Checks (.NET - main)

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  check-branch:
    uses: kikeiz/shared-workflows/.github/workflows/validate-branch-name.yml@v1
    with:
      branch_regex: '^(release|hotfix)/[A-Za-z0-9-]+$'

  verify:
    needs: check-branch
    uses: kikeiz/shared-workflows/.github/workflows/verify-dotnet.yml@v1