name: PR Checks (.NET - to develop or main)

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      valid_branch: ${{ steps.validate.outputs.valid_branch }}
    steps:
      - name: Validate source branch name
        id: validate
        run: |
          BRANCH="${{ github.head_ref }}"
          echo "Source branch: $BRANCH"
          regex="^(release|hotfix)/ACTO-[0-9]{4,5}(?:-[A-Za-z0-9]+)+$"
          if [[ "$BRANCH" =~ $regex ]]; then
            echo "✅ Valid branch: $BRANCH"
            echo "valid_branch=true" >> $GITHUB_OUTPUT
          else
            echo "⛔ Invalid branch: $BRANCH"
            echo "valid_branch=false" >> $GITHUB_OUTPUT
            exit 1
          fi

  verify:
    needs: check-branch
    if: needs.check-branch.outputs.valid_branch == 'true'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build & Test .NET
        run: |
          dotnet restore
          dotnet build
          dotnet test