name: Release to Staging (.NET)

on:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build and Test .NET
        run: |
          dotnet restore
          dotnet build
          dotnet test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Image
        id: build-image
        run: |
          IMAGE_TAG=release
          docker build -t ${{ secrets.ECR_REPO }}:$IMAGE_TAG -f Dockerfile .
          docker push ${{ secrets.ECR_REPO }}:$IMAGE_TAG
          echo "image=${{ secrets.ECR_REPO }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download and clean existing ECS task definition
        id: fetch-task
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ vars.TASK_DEFINITION }} \
            --region ${{ vars.AWS_REGION }} \
            --query 'taskDefinition' \
            --output json > taskdef.json

          jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          )' taskdef.json > taskdef-clean.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: taskdef-clean.json
          container-name: ${{ vars.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}
          environment-variables: |
            AWS_REGION=${{ vars.AWS_REGION }}
            QA_SQS_QUEUE_URL=${{ vars.QA_SQS_QUEUE_URL }}
            REMARKETING_SERVICE_QUEUE_URL=${{ vars.REMARKETING_SERVICE_QUEUE_URL }}
            ASPNETCORE_ENVIRONMENT=Staging
            QA_PROCESS_TABLE=${{ vars.QA_PROCESS_TABLE }}
            USER_TABLE=${{ vars.USER_TABLE }}
            MAX_NUM_PROCESSES=${{ vars.MAX_NUM_PROCESSES }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Cleanup task definition files
        run: rm -f taskdef.json taskdef-clean.json