name: Release to Staging (.NET)

on:
  push:
    branches:
      - release/*

jobs:
  build_and_test:
    uses: kikeiz/shared-workflows/.github/workflows/verify-dotnet.yml@v1
    with:
      dotnet_version: '9.0.x'

  build_and_push_image:
    needs: build_and_test
    uses: kikeiz/shared-workflows/.github/workflows/build-push-image.yml@v1
    with:
      image_tag: release
      environment: staging
    secrets: inherit

  export_vars:
    needs: build_and_push_image
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      AWS_REGION: ${{ steps.vars.outputs.AWS_REGION }}
      QA_SQS_QUEUE_URL: ${{ steps.vars.outputs.QA_SQS_QUEUE_URL }}
      REMARKETING_SERVICE_QUEUE_URL: ${{ steps.vars.outputs.REMARKETING_SERVICE_QUEUE_URL }}
      QA_PROCESS_TABLE: ${{ steps.vars.outputs.QA_PROCESS_TABLE }}
      USER_TABLE: ${{ steps.vars.outputs.USER_TABLE }}
      MAX_NUM_PROCESSES: ${{ steps.vars.outputs.MAX_NUM_PROCESSES }}
      IMAGE: ${{ steps.vars.outputs.IMAGE }}

    steps:
      - id: vars
        run: |
          echo "AWS_REGION=${{ vars.AWS_REGION }}" >> $GITHUB_OUTPUT
          echo "QA_SQS_QUEUE_URL=${{ vars.QA_SQS_QUEUE_URL }}" >> $GITHUB_OUTPUT
          echo "REMARKETING_SERVICE_QUEUE_URL=${{ vars.REMARKETING_SERVICE_QUEUE_URL }}" >> $GITHUB_OUTPUT
          echo "QA_PROCESS_TABLE=${{ vars.QA_PROCESS_TABLE }}" >> $GITHUB_OUTPUT
          echo "USER_TABLE=${{ vars.USER_TABLE }}" >> $GITHUB_OUTPUT
          echo "MAX_NUM_PROCESSES=${{ vars.MAX_NUM_PROCESSES }}" >> $GITHUB_OUTPUT
          echo "IMAGE=${{ vars.ECR_REPO }}:release" >> $GITHUB_OUTPUT
      
  deploy_to_ecs:
    needs: [export_vars, build_and_push_image]
    uses: kikeiz/shared-workflows/.github/workflows/deploy-ecs.yml@v1
    with:
      image: ${{ needs.export_vars.outputs.IMAGE }}
      environment: staging
      environment_variables: |
        AWS_REGION=${{ needs.export_vars.outputs.AWS_REGION }}
        QA_SQS_QUEUE_URL=${{ needs.export_vars.outputs.QA_SQS_QUEUE_URL }}
        REMARKETING_SERVICE_QUEUE_URL=${{ needs.export_vars.outputs.REMARKETING_SERVICE_QUEUE_URL }}
        ASPNETCORE_ENVIRONMENT=Staging
        QA_PROCESS_TABLE=${{ needs.export_vars.outputs.QA_PROCESS_TABLE }}
        USER_TABLE=${{ needs.export_vars.outputs.USER_TABLE }}
        MAX_NUM_PROCESSES=${{ needs.export_vars.outputs.MAX_NUM_PROCESSES }}
    secrets: inherit